import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const famousGames = [
    { nome: "Super Mario Bros.", desenvolvedor: "Nintendo", genero: "Plataforma", anoLancamento: 1985, preco: 109.95, descricao: "O jogo que salvou a indústria e definiu o gênero plataforma." },
    { nome: "The Legend of Zelda: Ocarina of Time", desenvolvedor: "Nintendo", genero: "Ação-Aventura", anoLancamento: 1998, preco: 274.95, descricao: "Considerado por muitos o melhor jogo de todos os tempos. Revolucionou o 3D." },
    { nome: "Tetris", desenvolvedor: "Alexey Pajitnov", genero: "Quebra-Cabeça", anoLancamento: 1984, preco: 27.45, descricao: "O clássico viciante de encaixar blocos." },
    { nome: "Doom", desenvolvedor: "id Software", genero: "FPS", anoLancamento: 1993, preco: 54.95, descricao: "Popularizou o gênero FPS e o multiplayer em rede." },
    { nome: "Pac-Man", desenvolvedor: "Namco", genero: "Arcade/Labirinto", anoLancamento: 1980, preco: 27.45, descricao: "Um dos jogos de arcade mais famosos de todos os tempos." },
    { nome: "Final Fantasy VII", desenvolvedor: "Square", genero: "JRPG", anoLancamento: 1997, preco: 219.95, descricao: "Elevou o JRPG a um novo patamar de popularidade e narrativa cinematográfica." },
    { nome: "Half-Life 2", desenvolvedor: "Valve", genero: "FPS", anoLancamento: 2004, preco: 109.95, descricao: "Um marco em física e narrativa nos jogos de tiro em primeira pessoa." },
    { nome: "Minecraft", desenvolvedor: "Mojang", genero: "Sandbox/Sobrevivência", anoLancamento: 2011, preco: 164.95, descricao: "Um fenômeno global que permite construir e explorar mundos infinitos de blocos." },
    { nome: "World of Warcraft", desenvolvedor: "Blizzard Entertainment", genero: "MMORPG", anoLancamento: 2004, preco: 82.50, descricao: "O MMORPG mais influente e duradouro da história." },
    { nome: "Grand Theft Auto V", desenvolvedor: "Rockstar Games", genero: "Ação-Aventura", anoLancamento: 2013, preco: 329.95, descricao: "Um sucesso de vendas e crítica com um vasto mundo aberto em Los Santos." },
    { nome: "The Witcher 3: Wild Hunt", desenvolvedor: "CD Projekt Red", genero: "RPG", anoLancamento: 2015, preco: 164.95, descricao: "Um RPG de mundo aberto com narrativa profunda e personagens marcantes." },
    { nome: "Red Dead Redemption 2", desenvolvedor: "Rockstar Games", genero: "Ação-Aventura", anoLancamento: 2018, preco: 329.95, descricao: "Um épico faroeste com atenção impecável aos detalhes." },
    { nome: "God of War", desenvolvedor: "Santa Monica Studio", genero: "Ação", anoLancamento: 2018, preco: 274.95, descricao: "Kratos retorna com seu filho Atreus em uma jornada nórdica emocionante." },
    { nome: "The Last of Us", desenvolvedor: "Naughty Dog", genero: "Ação-Aventura", anoLancamento: 2013, preco: 219.95, descricao: "Uma história tocante de sobrevivência e laços humanos em um mundo devastado." },
    { nome: "Dark Souls", desenvolvedor: "FromSoftware", genero: "RPG de Ação", anoLancamento: 2011, preco: 164.95, descricao: "Desafiador, recompensador e revolucionário em design de mundos interconectados." },
    { nome: "Overwatch", desenvolvedor: "Blizzard Entertainment", genero: "FPS", anoLancamento: 2016, preco: 164.95, descricao: "Um shooter em equipe vibrante que redefiniu o gênero." },
    { nome: "Fortnite", desenvolvedor: "Epic Games", genero: "Battle Royale", anoLancamento: 2017, preco: 0.00, descricao: "Um fenômeno cultural gratuito com milhões de jogadores." },
    { nome: "Among Us", desenvolvedor: "InnerSloth", genero: "Party/Social Deduction", anoLancamento: 2018, preco: 16.45, descricao: "Descubra o impostor em partidas divertidas e caóticas." },
    { nome: "Cyberpunk 2077", desenvolvedor: "CD Projekt Red", genero: "RPG de Ação", anoLancamento: 2020, preco: 274.95, descricao: "Um RPG futurista em mundo aberto com narrativa intensa." },
    { nome: "The Legend of Zelda: Breath of the Wild", desenvolvedor: "Nintendo", genero: "Ação-Aventura", anoLancamento: 2017, preco: 329.95, descricao: "Exploração e liberdade redefinem a franquia Zelda." },
    { nome: "Hades", desenvolvedor: "Supergiant Games", genero: "Roguelike", anoLancamento: 2020, preco: 109.95, descricao: "Um roguelike aclamado pela crítica com narrativa dinâmica e gameplay viciante." },
    { nome: "Elden Ring", desenvolvedor: "FromSoftware", genero: "RPG de Ação", anoLancamento: 2022, preco: 329.95, descricao: "Um vasto mundo aberto criado por Hidetaka Miyazaki e George R. R. Martin." },
    { nome: "Persona 5", desenvolvedor: "Atlus", genero: "JRPG", anoLancamento: 2016, preco: 219.95, descricao: "Um RPG estiloso e profundo sobre rebeldia e identidade." },
    { nome: "Metal Gear Solid", desenvolvedor: "Konami", genero: "Stealth/Ação", anoLancamento: 1998, preco: 164.95, descricao: "O título que popularizou o gênero stealth nos videogames." },
    { nome: "Street Fighter II", desenvolvedor: "Capcom", genero: "Luta", anoLancamento: 1991, preco: 54.95, descricao: "Revolucionou os jogos de luta e criou ícones como Ryu e Chun-Li." },
    { nome: "Resident Evil 4", desenvolvedor: "Capcom", genero: "Survival Horror", anoLancamento: 2005, preco: 164.95, descricao: "Mistura perfeita de ação e terror, reinventando a franquia." },
    { nome: "Skyrim", desenvolvedor: "Bethesda", genero: "RPG", anoLancamento: 2011, preco: 164.95, descricao: "Um dos RPGs mais jogados e modificados de todos os tempos." },
    { nome: "Halo: Combat Evolved", desenvolvedor: "Bungie", genero: "FPS", anoLancamento: 2001, preco: 109.95, descricao: "O título que definiu o padrão de FPS em consoles." },
    { nome: "Portal 2", desenvolvedor: "Valve", genero: "Puzzle/Plataforma", anoLancamento: 2011, preco: 109.95, descricao: "Um dos jogos de quebra-cabeça mais criativos e engraçados já feitos." },
    { nome: "Assassin’s Creed II", desenvolvedor: "Ubisoft", genero: "Ação-Aventura", anoLancamento: 2009, preco: 109.95, descricao: "A continuação que consolidou a série e apresentou Ezio Auditore." },
    { nome: "Uncharted 4: A Thief’s End", desenvolvedor: "Naughty Dog", genero: "Ação-Aventura", anoLancamento: 2016, preco: 274.95, descricao: "O encerramento épico da história de Nathan Drake." },
    { nome: "The Sims 4", desenvolvedor: "Maxis", genero: "Simulação", anoLancamento: 2014, preco: 164.95, descricao: "Simule a vida e crie histórias no famoso simulador social." },
    { nome: "League of Legends", desenvolvedor: "Riot Games", genero: "MOBA", anoLancamento: 2009, preco: 0.00, descricao: "Um dos maiores eSports do mundo." },
    { nome: "Valorant", desenvolvedor: "Riot Games", genero: "FPS Tático", anoLancamento: 2020, preco: 0.00, descricao: "Combina precisão de tiro e habilidades únicas em partidas 5x5." },
    { nome: "Apex Legends", desenvolvedor: "Respawn Entertainment", genero: "Battle Royale", anoLancamento: 2019, preco: 0.00, descricao: "Um battle royale rápido e estratégico no universo Titanfall." },
    { nome: "Genshin Impact", desenvolvedor: "HoYoverse", genero: "RPG de Ação", anoLancamento: 2020, preco: 0.00, descricao: "Um RPG de mundo aberto gratuito com belos visuais e narrativa envolvente." },
    { nome: "Super Mario 64", desenvolvedor: "Nintendo", genero: "Plataforma 3D", anoLancamento: 1996, preco: 164.95, descricao: "Definiu o padrão para jogos de plataforma 3D." },
    { nome: "Pokémon Red/Blue", desenvolvedor: "Game Freak", genero: "RPG", anoLancamento: 1996, preco: 82.50, descricao: "O início do fenômeno Pokémon." },
    { nome: "Chrono Trigger", desenvolvedor: "Square", genero: "JRPG", anoLancamento: 1995, preco: 137.45, descricao: "Um RPG com viagem no tempo e múltiplos finais aclamado pela crítica." },
    { nome: "Diablo II", desenvolvedor: "Blizzard North", genero: "RPG de Ação", anoLancamento: 2000, preco: 109.95, descricao: "O rei do 'loot' e um RPG de ação sombrio e viciante." },
    { nome: "StarCraft", desenvolvedor: "Blizzard Entertainment", genero: "Estratégia em Tempo Real (RTS)", anoLancamento: 1998, preco: 82.50, descricao: "Um dos jogos de estratégia mais competitivos e populares do mundo." },
    { nome: "Mass Effect 2", desenvolvedor: "BioWare", genero: "RPG de Ação", anoLancamento: 2010, preco: 137.45, descricao: "Um RPG de ficção científica com foco em escolhas e personagens." },
    { nome: "BioShock", desenvolvedor: "2K Boston", genero: "FPS/RPG", anoLancamento: 2007, preco: 109.95, descricao: "Uma obra-prima com atmosfera e narrativa únicas na cidade subaquática de Rapture." },
    { nome: "Borderlands 2", desenvolvedor: "Gearbox Software", genero: "RPG de Ação/FPS", anoLancamento: 2012, preco: 109.95, descricao: "O 'shooter-looter' que combinou humor, milhões de armas e cooperativo." },
    { nome: "Warcraft III: Reign of Chaos", desenvolvedor: "Blizzard Entertainment", genero: "RTS", anoLancamento: 2002, preco: 82.50, descricao: "Introduziu elementos de RPG a um jogo de estratégia, essencial para o gênero MOBA." },
    { nome: "God of War II", desenvolvedor: "Santa Monica Studio", genero: "Ação-Aventura", anoLancamento: 2007, preco: 54.95, descricao: "Considerado o ápice da franquia original de Kratos no PlayStation 2." },
    { nome: "Shadow of the Colossus", desenvolvedor: "Team Ico", genero: "Ação-Aventura", anoLancamento: 2005, preco: 164.95, descricao: "Uma jornada artística e emocional de combate a colossos gigantes." },
    { nome: "Monkey Island 2: LeChuck's Revenge", desenvolvedor: "LucasArts", genero: "Aventura Gráfica", anoLancamento: 1991, preco: 54.95, descricao: "Um clássico do 'point-and-click' com humor e quebra-cabeças icônicos." },
    { nome: "Day of the Tentacle", desenvolvedor: "LucasArts", genero: "Aventura Gráfica", anoLancamento: 1993, preco: 54.95, descricao: "Uma aventura no tempo hilária e visualmente marcante." },
    { nome: "SimCity 2000", desenvolvedor: "Maxis", genero: "Simulação/Construção", anoLancamento: 1993, preco: 27.45, descricao: "Um simulador de construção de cidades que marcou época." },
    { nome: "RollerCoaster Tycoon", desenvolvedor: "Chris Sawyer", genero: "Simulação/Estratégia", anoLancamento: 1999, preco: 54.95, descricao: "Crie e gerencie seu próprio parque de diversões." },
    { nome: "Age of Empires II: The Age of Kings", desenvolvedor: "Ensemble Studios", genero: "RTS", anoLancamento: 1999, preco: 82.50, descricao: "Um dos jogos de estratégia em tempo real mais amados e duradouros." },
    { nome: "Civilization V", desenvolvedor: "Firaxis Games", genero: "Estratégia 4X", anoLancamento: 2010, preco: 109.95, descricao: "Um jogo de estratégia baseado em turnos viciante e complexo." },
    { nome: "DOOM Eternal", desenvolvedor: "id Software", genero: "FPS", anoLancamento: 2020, preco: 164.95, descricao: "Ação frenética e brutal, honrando a tradição de DOOM." },
    { nome: "Death Stranding", desenvolvedor: "Kojima Productions", genero: "Ação-Aventura", anoLancamento: 2019, preco: 274.95, descricao: "O épico de Hideo Kojima sobre conexão em um mundo pós-apocalíptico." },
    { nome: "Marvel's Spider-Man", desenvolvedor: "Insomniac Games", genero: "Ação-Aventura", anoLancamento: 2018, preco: 274.95, descricao: "O melhor jogo do Homem-Aranha, com balanço de teia e combate fluidos." },
    { nome: "Ghosts of Tsushima", desenvolvedor: "Sucker Punch Productions", genero: "Ação-Aventura", anoLancamento: 2020, preco: 274.95, descricao: "Um épico samurai visualmente deslumbrante em mundo aberto." },
    { nome: "Demon's Souls", desenvolvedor: "FromSoftware", genero: "RPG de Ação", anoLancamento: 2009, preco: 219.95, descricao: "O precursor da série Souls, conhecido por sua dificuldade implacável." },
    { nome: "Sekiro: Shadows Die Twice", desenvolvedor: "FromSoftware", genero: "Ação-Aventura", anoLancamento: 2019, preco: 274.95, descricao: "Um jogo de ação focado em postura, deflexão e combates intensos." },
    { nome: "Bloodborne", desenvolvedor: "FromSoftware", genero: "RPG de Ação", anoLancamento: 2015, preco: 219.95, descricao: "Um RPG gótico e lovecraftiano com combate rápido e agressivo." },
    { nome: "Dishonored", desenvolvedor: "Arkane Studios", genero: "Stealth/Ação", anoLancamento: 2012, preco: 82.50, descricao: "Aventura 'stealth' com poderes sobrenaturais e escolhas morais." },
    { nome: "Prey", desenvolvedor: "Arkane Studios", genero: "FPS/RPG", anoLancamento: 2017, preco: 109.95, descricao: "Um 'immersive sim' de ficção científica em uma estação espacial infestada." },
    { nome: "Titanfall 2", desenvolvedor: "Respawn Entertainment", genero: "FPS", anoLancamento: 2016, preco: 54.95, descricao: "Campanha single-player aclamada e multiplayer de combate entre pilotos e Titãs." },
    { nome: "Rocket League", desenvolvedor: "Psyonix", genero: "Esporte/Ação", anoLancamento: 2015, preco: 0.00, descricao: "Futebol com carros a jato. Simples e viciante." },
    { nome: "Stardew Valley", desenvolvedor: "ConcernedApe", genero: "Simulação/RPG", anoLancamento: 2016, preco: 43.95, descricao: "Um jogo relaxante de fazenda inspirado em Harvest Moon." },
    { nome: "Cuphead", desenvolvedor: "Studio MDHR", genero: "Run and Gun/Plataforma", anoLancamento: 2017, preco: 82.50, descricao: "Arte inspirada em desenhos animados dos anos 30 e chefes difíceis." },
    { nome: "Ori and the Blind Forest", desenvolvedor: "Moon Studios", genero: "Metroidvania/Plataforma", anoLancamento: 2015, preco: 109.95, descricao: "Uma aventura de plataforma visualmente deslumbrante e emocional." },
    { nome: "Celeste", desenvolvedor: "Maddy Makes Games", genero: "Plataforma", anoLancamento: 2018, preco: 54.95, descricao: "Um jogo de plataforma difícil com uma história tocante sobre saúde mental." },
    { nome: "Undertale", desenvolvedor: "Toby Fox", genero: "RPG", anoLancamento: 2015, preco: 27.45, descricao: "Um RPG onde você não precisa matar ninguém. Escolhas importam." },
    { nome: "Disco Elysium", desenvolvedor: "ZA/UM", genero: "RPG", anoLancamento: 2019, preco: 109.95, descricao: "Um RPG com foco total em diálogo, habilidades e investigação." },
    { nome: "Return of the Obra Dinn", desenvolvedor: "Lucas Pope", genero: "Quebra-Cabeça/Mistério", anoLancamento: 2018, preco: 82.50, descricao: "Um mistério de dedução em um navio fantasma com estilo visual único." },
    { nome: "Subnautica", desenvolvedor: "Unknown Worlds Entertainment", genero: "Sobrevivência/Aventura", anoLancamento: 2018, preco: 109.95, descricao: "Explore e sobreviva em um oceano alienígena." },
    { nome: "No Man's Sky", desenvolvedor: "Hello Games", genero: "Aventura/Sobrevivência", anoLancamento: 2016, preco: 164.95, descricao: "Exploração de um universo de ficção científica com bilhões de planetas." },
    { nome: "Forza Horizon 5", desenvolvedor: "Playground Games", genero: "Corrida/Mundo Aberto", anoLancamento: 2021, preco: 274.95, descricao: "Um dos melhores jogos de corrida de mundo aberto, ambientado no México." },
    { nome: "Gran Turismo 4", desenvolvedor: "Polyphony Digital", genero: "Simulação de Corrida", anoLancamento: 2004, preco: 54.95, descricao: "Um simulador de direção clássico e detalhado do PS2." },
    { nome: "Tekken 3", desenvolvedor: "Namco", genero: "Luta", anoLancamento: 1997, preco: 54.95, descricao: "Um dos jogos de luta 3D mais influentes e aclamados." },
    { nome: "Mortal Kombat II", desenvolvedor: "Midway Games", genero: "Luta", anoLancamento: 1993, preco: 54.95, descricao: "Violência e Fatalities que definiram uma geração." },
    { nome: "Super Smash Bros. Melee", desenvolvedor: "HAL Laboratory", genero: "Luta de Plataforma", anoLancamento: 2001, preco: 109.95, descricao: "O título de eSports que popularizou a série Smash Bros." },
    { nome: "Tony Hawk's Pro Skater 2", desenvolvedor: "Neversoft", genero: "Esporte Extremo/Arcade", anoLancamento: 2000, preco: 54.95, descricao: "O ápice dos jogos de skate, com manobras e trilha sonora lendárias." },
    { nome: "The Elder Scrolls III: Morrowind", desenvolvedor: "Bethesda Game Studios", genero: "RPG", anoLancamento: 2002, preco: 82.50, descricao: "Um RPG complexo e atmosférico em um mundo exótico." },
    { nome: "Fallout: New Vegas", desenvolvedor: "Obsidian Entertainment", genero: "RPG de Ação", anoLancamento: 2010, preco: 109.95, descricao: "Um RPG pós-apocalíptico com profundo foco em escolhas de jogador." },
    { nome: "Deus Ex", desenvolvedor: "Ion Storm", genero: "FPS/RPG", anoLancamento: 2000, preco: 54.95, descricao: "Um 'immersive sim' futurista que inovou em liberdade de escolhas." },
    { nome: "System Shock 2", desenvolvedor: "Irrational Games", genero: "FPS/RPG", anoLancamento: 1999, preco: 54.95, descricao: "Aclamado jogo de terror e ficção científica, precursor de BioShock." },
    { nome: "Kerbal Space Program", desenvolvedor: "Squad", genero: "Simulação Espacial", anoLancamento: 2015, preco: 82.50, descricao: "Construa e lance foguetes para explorar o espaço." },
    { nome: "Factorio", desenvolvedor: "Wube Software", genero: "Simulação/Estratégia", anoLancamento: 2020, preco: 109.95, descricao: "Um jogo de construção de fábricas infinitamente viciante." },
    { nome: "Detroit: Become Human", desenvolvedor: "Quantic Dream", genero: "Aventura Cinemática", anoLancamento: 2018, preco: 219.95, descricao: "Um thriller de ficção científica focado em escolhas e narrativas ramificadas." },
    { nome: "Heavy Rain", desenvolvedor: "Quantic Dream", genero: "Aventura Cinemática", anoLancamento: 2010, preco: 109.95, descricao: "Investigação sombria com consequências diretas das suas escolhas." },
    { nome: "Life Is Strange", desenvolvedor: "Dontnod Entertainment", genero: "Aventura Episódica", anoLancamento: 2015, preco: 54.95, descricao: "Uma história sobre amizade, viagem no tempo e o efeito borboleta." },
    { nome: "Limbo", desenvolvedor: "Playdead", genero: "Quebra-Cabeça/Plataforma", anoLancamento: 2010, preco: 27.45, descricao: "Um jogo de plataforma em preto e branco com atmosfera sombria." },
    { nome: "Inside", desenvolvedor: "Playdead", genero: "Quebra-Cabeça/Plataforma", anoLancamento: 2016, preco: 54.95, descricao: "Sucessor espiritual de Limbo, com gráficos estonteantes e narrativa misteriosa." },
    { nome: "Journey", desenvolvedor: "Thatgamecompany", genero: "Aventura Artística", anoLancamento: 2012, preco: 54.95, descricao: "Uma jornada visual e emocional com multiplayer sutil." },
    { nome: "Firewatch", desenvolvedor: "Campo Santo", genero: "Aventura em Primeira Pessoa", anoLancamento: 2016, preco: 54.95, descricao: "Uma história sobre isolamento e comunicação em uma floresta." },
    { nome: "What Remains of Edith Finch", desenvolvedor: "Giant Sparrow", genero: "Aventura em Primeira Pessoa", anoLancamento: 2017, preco: 54.95, descricao: "Uma coleção de contos estranhos e maravilhosos sobre a família Finch." },
    { nome: "Disco Elysium - The Final Cut", desenvolvedor: "ZA/UM", genero: "RPG", anoLancamento: 2021, preco: 109.95, descricao: "A edição definitiva do aclamado RPG com dublagem completa." },
    { nome: "Nier: Automata", desenvolvedor: "PlatinumGames", genero: "RPG de Ação", anoLancamento: 2017, preco: 164.95, descricao: "Combate estiloso e uma narrativa filosófica e complexa." },
    { nome: "Divinity: Original Sin 2", desenvolvedor: "Larian Studios", genero: "CRPG", anoLancamento: 2017, preco: 109.95, descricao: "Um RPG clássico com combate tático e grande liberdade de escolhas." },
    { nome: "Baldur's Gate 3", desenvolvedor: "Larian Studios", genero: "CRPG", anoLancamento: 2023, preco: 329.95, descricao: "O aclamado RPG que reviveu o gênero CRPG com base em D&D." },
    { nome: "Marvel's Guardians of the Galaxy", desenvolvedor: "Eidos-Montréal", genero: "Ação-Aventura/RPG", anoLancamento: 2021, preco: 219.95, descricao: "Uma aventura espacial com foco em narrativa e combate em equipe." },
    { nome: "It Takes Two", desenvolvedor: "Hazelight Studios", genero: "Plataforma/Cooperativo", anoLancamento: 2021, preco: 164.95, descricao: "Um jogo cooperativo obrigatório com mecânicas em constante mudança." },
    { nome: "A Way Out", desenvolvedor: "Hazelight Studios", genero: "Ação/Cooperativo", anoLancamento: 2018, preco: 109.95, descricao: "Uma história de fuga da prisão, jogável apenas em cooperativo." },
    { nome: "Dead Space (2023)", desenvolvedor: "Motive Studio", genero: "Survival Horror/Ação", anoLancamento: 2023, preco: 299.95, descricao: "Remake aterrorizante do clássico de survival horror espacial." },
    { nome: "Alien: Isolation", desenvolvedor: "Creative Assembly", genero: "Survival Horror", anoLancamento: 2014, preco: 109.95, descricao: "Um jogo de terror baseado em 'stealth' contra um Alien implacável." },
    { nome: "Amnesia: The Dark Descent", desenvolvedor: "Frictional Games", genero: "Survival Horror", anoLancamento: 2010, preco: 54.95, descricao: "Um marco do terror moderno focado em esconderijo e sanidade." },
    { nome: "Resident Evil 7: Biohazard", desenvolvedor: "Capcom", genero: "Survival Horror", anoLancamento: 2017, preco: 109.95, descricao: "Revitalizou a franquia com uma perspectiva em primeira pessoa." },
    { nome: "Silent Hill 2", desenvolvedor: "Konami", genero: "Survival Horror", anoLancamento: 2001, preco: 82.50, descricao: "Aclamado por sua profunda narrativa psicológica e terror atmosférico." },
    { nome: "Outlast", desenvolvedor: "Red Barrels", genero: "Survival Horror", anoLancamento: 2013, preco: 54.95, descricao: "Terror em primeira pessoa onde você só pode correr e se esconder." },
];

export async function seedJogos(prisma) {
    console.log("🌎 Iniciando o seed com 100 jogos (valores em reais)...");

    const dataToInsert = famousGames.map((jogo) => ({
        nome: jogo.nome,
        desenvolvedor: jogo.desenvolvedor,
        genero: jogo.genero,
        anoLancamento: jogo.anoLancamento,
        preco: String(jogo.preco),
        descricao: jogo.descricao.substring(0, 500),
    }));

    const { count } = await prisma.jogo.createMany({
        data: dataToInsert,
        skipDuplicates: true,
    });

    console.log(`✅ Seed concluído. ${count} jogos criados/verificados na tabela 'jogo'.`);
    return count;
}